RH/RH.WEB/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RH.BLL;
using RH.Entidades;
using Common.Enums;
using FiltrosWeb;

namespace RH.WEB.Controllers
{
    public class ClientesController : Controller
    {
        readonly Clientes _emp = new Clientes();
        readonly Empresas _rp = new Empresas();
        readonly Departamentos _depto = new Departamentos();
        readonly Estados _edo = new Estados();

        #region "CLIENTES CREAR - EDITAR - CONSULTAR"

        // GET: Empresas
        [AccesoModuloAttribute(Modulo = Modulos.RHClientes, Accion = AccionCrud.Consultar)]
        public ActionResult Index()
        {
            var modelo = _emp.GetClientes();
            return View(modelo);
        }

        [AccesoModuloAttribute(Modulo = Modulos.RHClientes, Accion = AccionCrud.Agregar)]
        public ActionResult Create()
        {
            var registros = _rp.GetRegistrosPatronales();
            ViewBag.SelectListRP = registros;

            var departamentos = _depto.GetDepartamentos();
            ViewBag.SelectListDepto = departamentos;

            return View();
        }

        //[HttpPost]
        //[AccesoModuloAttribute(Modulo = Modulos.Clientes, Accion = AccionCrud.Agregar)]
        //public ActionResult Create(Cliente regsCliente, List<int> itemsRP, List<int> itemsDP)
        //{
        //    try
        //    {
        //       _emp.GuardarCliente(regsCliente, itemsRP, itemsDP);

        //        return RedirectToAction("Index");
        //    }
        //    catch (Exception e)
        //    {

        //        return View();
        //    }
        //}


        [AccesoModuloAttribute(Modulo = Modulos.RHClientes, Accion = AccionCrud.Agregar)]
        public ActionResult CrearVP()
        {
            var registros = _rp.GetRegistrosPatronales();
            var Fis_Asi = registros.Where(x => x.RegistroPatronal != null).ToList();
            var Com_Asim = registros.Where(x => x.RegistroPatronal == null).ToList();

            ViewBag.SelectListFis_Asim = Fis_Asi;
            ViewBag.SelectListComp_Sind = Com_Asim;
            var departamentos = _depto.GetDepartamentos();
            ViewBag.SelectListDepto = departamentos;

            return PartialView();
        }

        [HttpPost]
        [AccesoModuloAttribute(Modulo = Modulos.RHClientes, Accion = AccionCrud.Agregar)]
        public ActionResult CrearVP(Cliente regsCliente, List<int> itemsRP, List<int> itemsCom,List<int> itemsAsim , List<int> itemsSin,  List<int> itemsDP)
        {
            try
            {
                _emp.GuardarCliente(regsCliente, itemsDP);

                return RedirectToAction("Index");
            }
            catch (Exception )
            {

                return View();
            }
        }


        [AccesoModuloAttribute(Modulo = Modulos.RHClientes, Accion = AccionCrud.Editar)]
        public ActionResult EditarVP(int idCliente)
        {

            var modelo = _emp.GetClienteById(idCliente);

       
            var slEmpDep = _emp.GetClienteDepartamentos(idCliente);

   
            ViewBag.SelectListDepto = slEmpDep;     

            return PartialView(modelo);
        }


        [AccesoModuloAttribute(Modulo = Modulos.RHClientes, Accion = AccionCrud.Editar)]
        [HttpPost]
        public ActionResult EditarVP(Cliente regsEmpresa, List<int> itemsRP, List<int> itemsDP,List<int> itemsAsim,List<int> itemsSin,List<int> itemsCom, int idcliente)
        {
            try
            {
                _emp.ActualizarCliente(regsEmpresa,itemsDP,idcliente);

                return RedirectToAction("Index");
            }
            catch (Exception )
            {

                return View();
            }
        }

        public ActionResult DetalleVP(int idCliente)
        {

            var departamentos = _emp.DetallesDepartamentos(idCliente);
            var cliente = _emp.GetClienteById(idCliente);

            ViewBag.SelectListDepto = departamentos;
            ViewBag.Clientes = cliente.Nombre;
            return PartialView();
        }

        #endregion

        #region "SUCURSALES CREAR - EDITAR - CONSULTAR"

        [AccesoModulo(Modulo = Modulos.RHClientes, Accion = AccionCrud.Consultar)]
        public ActionResult IndexSucursales(int idCliente)
        {
            var empresa = _emp.GetClienteById(idCliente);
            var sucursales = _emp.GetSucursalesByIdCliente(idCliente);

            ViewBag.Empresa = empresa;
            return View(sucursales);
        }

        [AccesoModulo(Modulo = Modulos.RHClientes, Accion = AccionCrud.Agregar)]
        public ActionResult CrearSucursalVP(int idCliente)
        {
            

             var listaEstados = _edo.GetEstados();
            var listaZonas = _emp.GetZonaSalario();

            var selectListEstados = listaEstados.Select(x => new SelectListItem()
            {
                Value = x.IdEstado.ToString(),
                Text = x.Descripcion,
                Selected = (x.IdEstado == 1)
            }).ToList();


            var selectListZonas = listaZonas.Select(x => new SelectListItem()
            {
                Value = x.IdZonaSalario.ToString(),
                Text = x.Zona + " - " + x.SMG,
                Selected = (x.IdZonaSalario == 1)
            }).ToList();


            
            ViewBag.SelectListZonas = selectListZonas;
            ViewBag.SelectListEstados = selectListEstados;
            
            ViewBag.EmpresaId = idCliente;

            //Listado de Empresas
            var registros = _rp.GetRegistrosPatronales();
            var Fis_Asi = registros.Where(x => x.RegistroPatronal != null).ToList();
            var Com_Asim = registros.Where(x => x.RegistroPatronal == null).ToList();

            ViewBag.SelectListFis_Asim = Fis_Asi;
            ViewBag.SelectListComp_Sind = Com_Asim;


            return PartialView();
        }


        [AccesoModulo(Modulo = Modulos.RHClientes, Accion = AccionCrud.Agregar)]
        [HttpPost]
        public ActionResult CrearSucursalVP(Sucursal sucursal, List<int> itemsRP, List<int> itemsCom, List<int> itemsAsim, List<int> itemsSin)
        {
            try
            {
                _emp.GuardarSucursalCliente(sucursal, itemsRP,itemsCom,itemsAsim,itemsSin);

                return RedirectToAction("IndexSucursales", new { idCliente = sucursal.IdCliente});
            }
            catch (Exception )
            {

                return View();
            }
        }

        [AccesoModulo(Modulo = Modulos.RHClientes, Accion = AccionCrud.Editar)]
        public ActionResult EditarSucursalVP(int idSucursal)
        {
            var sucursal = _emp.GetSucursalClienteById(idSucursal);

            var listaEstados = _edo.GetEstados();
            var listaZonas = _emp.GetZonaSalario();
            
            var selectListEstados = listaEstados.Select(e => new SelectListItem()
            {
                Value = e.IdEstado.ToString(), Text = e.Descripcion, Selected = (e.IdEstado == sucursal.IdEstado)
            }).ToList();


            var selectListZonas = listaZonas.Select(z => new SelectListItem()
            {
                Value = z.IdZonaSalario.ToString(),
                Text = z.Zona +" - "+ z.SMG,
                Selected = (z.IdZonaSalario == sucursal.IdSucursal)
            }).ToList();

            var EmpFIs = _emp.GetSucursalEmpresaSeleccionada(idSucursal, 1, 1);
            var EmpAsim = _emp.GetSucursalEmpresaSeleccionada(idSucursal, 1, 4);
            var EmpCom = _emp.GetSucursalEmpresaSeleccionada(idSucursal, 2, 2);
            var EmpSin = _emp.GetSucursalEmpresaSeleccionada(idSucursal, 2, 3);
            

            ViewBag.SelectListFis = EmpFIs;
            ViewBag.SelectListAsim = EmpAsim;
            ViewBag.SelectListRPCom = EmpCom;
            ViewBag.SelectListRPSIn = EmpSin;



            ViewBag.SelectListZonas = selectListZonas;
            ViewBag.SelectListEstados = selectListEstados;

            

            return PartialView(sucursal);
        }

        [AccesoModulo(Modulo = Modulos.RHClientes, Accion = AccionCrud.Editar)]
        [HttpPost]
        public ActionResult EditarSucursalVP(Sucursal sucursal, List<int> itemsRP, List<int> itemsAsim, List<int> itemsSin, List<int> itemsCom)
        {
            _emp.ActualizarSucursal(sucursal, itemsRP,itemsAsim,itemsSin,itemsCom);

            return RedirectToAction("IndexSucursales", new { idCliente = sucursal.IdCliente });
        }



        [AccesoModulo(Modulo = Modulos.RHClientes, Accion = AccionCrud.Consultar)]
        public ActionResult DetalleSucursalVP(int idSucursal)
        {
            var sucursal = _emp.GetSucursalClienteById(idSucursal);
            var empresas = _emp.DetalleSucursal(idSucursal);




            //ViewBag.SelectListRP = listaRP.Where(x => x.Seleccionado == true).ToList();
            ViewBag.Empresas = empresas;

            return PartialView(sucursal);
        }


        #endregion

    }
}

RH/RH.WEB/Views/Clientes/CrearSucursalVP.cshtml
@using Common.Helpers
@using RH.BLL
@using RH.Entidades;
@model RH.Entidades.Sucursal

@{

    var selectListZonas = ViewBag.SelectListZonas;
    var selectListEstados = ViewBag.SelectListEstados;
    var listaRP = ViewBag.ListRP as List<ClienteEmpresas>;
    var slRp = ViewBag.SelectListFis_Asim as List<Empresa>;

    var EmpCom = ViewBag.SelectListComp_Sind as List<Empresa>;
    var slDepto = ViewBag.SelectListDepto as List<Departamento>;

    var clienteId =  ViewBag.EmpresaId;
}
<style>
  .modal-dialog {
        width: 1100px !important;
    }

    select.selectpicker {
        display: block !important;
        float: left;
        overflow: hidden;
        height: 34px;
        width: 0;
        border: 0;
        padding: 0;
        box-shadow: none;
        color: white;
    }
</style>

<link href="~/Content/tablas/tamaño.css" rel="stylesheet" />
<link href="~/Content/bootstrap-select.css" rel="stylesheet" type="text/css" />
<!-- CSS para el tooltip validator -->
<link rel="stylesheet" href="~/Content/validator/TooltipValidator.css" />

<div id="divContenido2">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><i class="fa fa-plus"></i> Nueva Sucursal</h4>
    </div>

    @using (Html.BeginForm("CrearSucursalVP", "Clientes", FormMethod.Post, new { id = "SucursalFrm", @class = "tooltipForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="panel panel-default" id="create">
            <input type="hidden" id="IdCliente" name="IdCliente" value="@clienteId" />
            <div class="panel-body">
                <div class="form-horizontal">
                    <div class="col-md-6 col-xs-12">
                        <div class="form-group">
                            <label class="col-md-4 "> Estado </label>
                            <div class="col-md-8">
                                @HtmlLocalHelper.ComboBox(selectListEstados, "IdEstado", htmlAttributes: new Dictionary<string, object>() { { "data-rule-required", true }@*, { "tabIndex", 1 }*@ })
</div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 "> Nombre de la Sucursal </label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="Ciudad" id="Ciudad"
                                       data-rule-required="true"
                                       data-rule-maxlength="50"
                                       data-rule-minlength="3" 
                                       @*tabindex="2"*@
                                       />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 "> Zona Salario </label>
                            <div class="col-md-8">
                                @HtmlLocalHelper.ComboBox(selectListZonas, "IdZonaSalario", htmlAttributes: new Dictionary<string, object>() { { "data-rule-required", true }@*, { "tabIndex", 3 }*@ })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12">
                        <div class="form-group">
                            <label class="col-md-4">Empresas Fiscales</label>
                            <div class="col-md-8">

                                <select class="form-control selectpicker show-tick" @*tabindex="4"*@ name="itemsRP" multiple id="itemsRP" data-width="330px" data-actions-box="true" data-live-search="true" title="Selecciona la configuración" data-selected-text-format="count">
                                    @if (slRp != null)
                                    {
                                        foreach (var item in slRp)
                                        {
                                            <option value="@item.IdEmpresa">@item.RazonSocial</option>
                                        }
                                    }

                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4">Empresas Complementos</label>
                            <div class="col-md-8">
                                <select id="itemsCom" name="itemsCom" class="selectpicker show-tick" @*tabindex="5"*@ multiple data-width="330px" data-actions-box="true" data-live-search="true" title="Selecciona la configuración" data-selected-text-format="count">

                                    @if (EmpCom != null)
                                    {
                                        foreach (var item in EmpCom)
                                        {
                                            <option value="@item.IdEmpresa">@item.RazonSocial</option>
                                        }
                                    }

                                </select>


                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-md-4">Empresas Sindicato</label>
                            <div class="col-md-8">
                                <select id="itemsSin" name="itemsSin" class="selectpicker show-tick" @*tabindex="6"*@ multiple data-width="330px" data-actions-box="true" data-live-search="true" title="Selecciona la configuración" data-selected-text-format="count">

                                    @if (EmpCom != null)
                                    {
                                        foreach (var item in EmpCom)
                                        {
                                            <option value="@item.IdEmpresa">@item.RazonSocial</option>
                                        }
                                    }

                                </select>


                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-md-4">Empresa Asimilado</label>
                            <div class="col-md-8">
                                <select id="itemsAsim" name="itemsAsim" class="selectpicker show-tick" @*tabindex="7"*@ multiple data-width="330px" data-actions-box="true" data-live-search="true" title="Selecciona la configuración" data-selected-text-format="count">

                                    @if (slRp != null)
                                    {
                                        foreach (var item in slRp)
                                        {
                                            <option value="@item.IdEmpresa">@item.RazonSocial</option>
                                        }
                                    }

                                </select>


                            </div>

                        </div>

                    </div>


                        
                    </div>
               
                    



              
            </div>
        </div>
        <div class="modal-footer">
            <input type="submit" id="idGuardar" class="btn btn-primary input-group-sm" value="Guardar" />
             <button type="button" class="btn btn-danger" @*tabindex="9"*@ data-dismiss="modal">Cancelar</button>
        </div>
    }

    <script src="~/Scripts/validator/jquery.validate.1.15.js"></script>
    <script src="~/Scripts/validator/messages_es.js"></script>
    <script src="~/Scripts/validator/TooltipValidator.js"></script>
    <script src="~/Scripts/bootstrap-multiselect.js"></script>
    <script src="~/Scripts/bootstrap-select.min.js"></script>
    <script src="~/Scripts/i18n/defaults-es_CL.js"></script>
    <script>

        $(document).ready(function () {
            var orderCount = 0;
      
            $(".selectpicker").selectpicker();


        });


    </script>

</div>

RH/RH.WEB/Views/Clientes/DetalleSucursalVP.cshtml
@using RH.BLL
@model RH.BLL.SucursalCliente


@{
    ViewBag.Title = "Detalle Sucursal";
    var empresas = ViewBag.Empresas as List<SucursalEmpresas>;
}

<style>
    .modal-dialog {
        width: 1100px !important;
    }

    .panel-heading {
        color: black !important;
    }

    small {
        font-size: 13.5px;
    }

    div.scroll {
        width: 350px;
        height: 120px;
        overflow-y: scroll;
    }
</style>

<div id="divContenido2">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><i class="fa fa-info-circle fa-lg"></i> Detalle Sucursal </h4>
    </div>


    <div class="panel panel-default" id="detail">
        <div class="panel-body">
            <div class="form-horizontal">
                <div class="col-md-12 col-xs-12">
                    <div class="form-group">
                        <label class="col-md-2">Cliente</label>
                        <input type="text" class="col-md-4" value="@Model.NomCliente" disabled />
                        
                        <label class="col-md-2">Nombre de la Sucursal</label>
                        <input type="text" class="col-md-4" value="@Model.Ciudad" disabled />

                    </div>
                    <div class="form-group">
                        <label class="col-md-2">Estado</label>
                        <input type="text" class="col-md-4" value="@Model.Estado" disabled />

                        <label class="col-md-2">Zona Salario</label>
                        <input type="text" class="col-md-4" value="@Model.ZonaSalario - @Model.ValorZonaSalario" disabled />

                    </div>
                    <div class="form-group">
                        <label class="col-md-2">Empresas Fiscales</label>
                        <div class="col-md-4 scroll">
                            <ul>
                                @foreach (var a in empresas.Where(x => x.Esquema == 1))
                                {
                                    <li>   <small>@a.NombreEmpresa</small></li>
                                }
                            </ul>

                        </div>
                        <label class="col-md-2">Empresas Complementos</label>
                        <div class="col-md-4 scroll">
                            <ul>
                                @foreach (var a in empresas.Where(x => x.Esquema == 2))
                                {
                                    <li>   <small>@a.NombreEmpresa</small></li>
                                }
                            </ul>

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2">Empresas Asimilado</label>
                        <div class="col-md-4 scroll">
                            <ul>
                                @foreach (var a in empresas.Where(x => x.Esquema == 4))
                                {
                                    <li>   <small>@a.NombreEmpresa</small></li>
                                }
                            </ul>
                        </div>
                        <label class="col-md-2">Empresas Sindicato</label>
                        <div class="col-md-4 scroll">
                            <ul>
                                @foreach (var a in empresas.Where(x => x.Esquema == 3))
                                {
                                    <li>   <small>@a.NombreEmpresa</small></li>
                                }
                            </ul>

                        </div>
                    </div>
                </div>
               
            </div>
          

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    </div>
</div>

RH/RH.WEB/Views/Clientes/EditarSucursalVP.cshtml
@using Common.Helpers
@using RH.BLL
@model RH.BLL.SucursalCliente

@{

    var selectListZonas = ViewBag.SelectListZonas;
    var selectListEstados = ViewBag.SelectListEstados;
    var listadoFis = ViewBag.SelectListFis as List<SucursalEmpresas>;
    var listadoAsim = ViewBag.SelectListAsim as List<SucursalEmpresas>;
    var listadoCom = ViewBag.SelectListRPCom as List<SucursalEmpresas>;
    var listadoSin = ViewBag.SelectListRPSIn as List<SucursalEmpresas>;
    var listaRP = ViewBag.ListRP as List<SucursalEmpresas>;

}

<link href="~/Content/tablas/tamaño.css" rel="stylesheet" />

<link rel="stylesheet" href="~/Content/validator/TooltipValidator.css" />
<link href="~/Content/bootstrap-select.css" rel="stylesheet" type="text/css" />
<style>
    .modal-dialog {
        width: 1100px !important;
    }

    select.selectpicker {
        display: block !important;
        float: left;
        overflow: hidden;
        height: 34px;
        width: 0;
        border: 0;
        padding: 0;
        box-shadow: none;
        color: white;
    }
</style>
<div id="divContenido2">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><i class="glyphicon glyphicon-pencil"></i> Editar Sucursal</h4>
    </div>

    @using (Html.BeginForm("EditarSucursalVP", "Clientes", FormMethod.Post, new { id = "SucursalFrm", @class = "tooltipForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="panel panel-default" id="edit">
            <div class="panel-body">
                <div class="form-horizontal">
                    <div>
                        @Html.HiddenFor(model => model.IdSucursal, new { htmlAttributes = new { @class = "form-control" } })
                    </div>

                    <div>
                        @Html.HiddenFor(model => model.IdCliente, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <div class="col-md-6 col-xs-12">
                        <div class="form-group">
                            <label class="col-md-4 "> Estado </label>
                            <div class="col-md-8">
                                @HtmlLocalHelper.ComboBox(selectListEstados, "IdEstado", htmlAttributes: new Dictionary<string, object>() { { "data-rule-required", true } })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 ">Nombre de la Sucursal </label>
                           @* @Html.LabelFor(model => model.Ciudad, htmlAttributes: new { @class = "col-md-4" })*@
                            <div class="col-md-8">
                                @*@Html.EditorFor(model => model.Ciudad, new { htmlAttributes = new { @class = "form-control" } })*@
                                <input type="text" class="form-control" name="Ciudad" id="Ciudad" value="@Model.Ciudad"
                                       data-rule-required="true"
                                       data-rule-maxlength="50"
                                       data-rule-minlength="3" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 "> Zona Salario </label>
                            <div class="col-md-8">
                                @HtmlLocalHelper.ComboBox(selectListZonas, "IdZonaSalario", htmlAttributes: new Dictionary<string, object>() { { "data-rule-required", true } })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12">
                        <div class="form-group">
                            <label class="col-md-4">Empresas Fiscales</label>
                            <div class="col-md-8">

                                <select class="form-control selectpicker show-tick" name="itemsRP" multiple id="itemsRP" data-width="330px" data-actions-box="true" data-live-search="true" title="Selecciona la configuración" data-selected-text-format="count">
                                
                                        @if (listadoFis != null)
                                        {

                                            foreach (var item in listadoFis)
                                            {
                                                if (item.Seleccionado)
                                                {
                                                    <option value="@item.IdEmpresa" selected="selected">@item.NombreEmpresa</option>
                                                }
                                                else
                                                {
                                                    <option value="@item.IdEmpresa">@item.NombreEmpresa</option>
                                                }

                                            }
                                        }

                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4">Empresas Complementos</label>
                            <div class="col-md-8">
                                <select id="itemsCom" name="itemsCom" class="selectpicker show-tick" multiple data-width="330px" data-actions-box="true" data-live-search="true" title="Selecciona la configuración" data-selected-text-format="count">

                                    @if (listadoCom != null)
                                    {

                                        foreach (var item in listadoCom)
                                        {
                                            if (item.Seleccionado)
                                            {
                                                <option value="@item.IdEmpresa" selected="selected">@item.NombreEmpresa</option>
                                            }
                                            else
                                            {
                                                <option value="@item.IdEmpresa">@item.NombreEmpresa</option>
                                            }

                                        }
                                    }
                                </select>


                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-md-4">Empresas Sindicato</label>
                            <div class="col-md-8">
                                <select id="itemsSin" name="itemsSin" class="selectpicker show-tick" multiple data-width="330px" data-actions-box="true" data-live-search="true" title="Selecciona la configuración" data-selected-text-format="count">
                                    
                                    @if (listadoSin != null)
                                    {

                                        foreach (var item in listadoSin)
                                        {
                                            if (item.Seleccionado)
                                            {
                                                <option value="@item.IdEmpresa" selected="selected">@item.NombreEmpresa</option>
                                            }
                                            else
                                            {
                                                <option value="@item.IdEmpresa">@item.NombreEmpresa</option>
                                            }

                                        }
                                    }

                                </select>


                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-md-4">Empresa Asimilado</label>
                            <div class="col-md-8">
                                <select id="itemsAsim" name="itemsAsim" class="selectpicker show-tick" multiple data-width="330px" data-actions-box="true" data-live-search="true" title="Selecciona la configuración" data-selected-text-format="count">

                                    @if (listadoAsim != null)
                                    {

                                        foreach (var item in listadoAsim)
                                        {
                                            if (item.Seleccionado)
                                            {
                                                <option value="@item.IdEmpresa" selected="selected">@item.NombreEmpresa</option>
                                            }
                                            else
                                            {
                                                <option value="@item.IdEmpresa">@item.NombreEmpresa</option>
                                            }

                                        }
                                    }

                                </select>


                            </div>

                        </div>

                    </div>



                </div>




             
            </div>
        </div>
        <div class="modal-footer">
            <input type="submit" id="idGuardar" class="btn btn-primary input-group-sm" value="Guardar" /> <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
        </div>
    }

    <script src="~/Scripts/validator/jquery.validate.1.15.js"></script>
    <script src="~/Scripts/validator/messages_es.js"></script>
    <script src="~/Scripts/validator/TooltipValidator.js"></script>
    

    <script src="~/Scripts/bootstrap-multiselect.js"></script>
    <script src="~/Scripts/bootstrap-select.min.js"></script>
    <script>

        $(document).ready(function () {
            var orderCount = 0;

            $(".selectpicker").selectpicker();


        });


    </script>

</div>